# Generated by Django 3.1.7 on 2021-05-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0003_auto_20210508_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='number_of_points',
            field=models.IntegerField(),
        ),
    ]
